[package]
name = "hello-world"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
panic-halt = { version = "0.2.0" }

zephyr-sys = { path = "../../crates/zephyr-sys" }

