[package]
name = "hello-world"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
panic-halt = "0.2.0"


[profile.release]
codegen-units = 1
debug = true
lto = true
panic = "abort"

[profile.dev]
panic = "abort"